package db.dto;
// Generated Mar 4, 2013 12:27:59 AM by Hibernate Tools 3.2.1.GA



/**
 * Breakup generated by hbm2java
 */
public class Breakup  implements java.io.Serializable {


     private Integer id;
     private Profile profile;
     private Integer category;
     private String category_id;
     private String label;
     private String color;
     private String path;
     private String projects_backed;
     private Integer count;
    public Breakup() {
    }

    
    public Breakup(Profile profile) {
        this.profile = profile;
    }
    public Breakup(Profile profile, String category_id, String label, String color, String path, String projects_backed) {
       this.profile = profile;
       this.category_id = category_id;
       this.label = label;
       this.color = color;
       this.path = path;
       this.projects_backed = projects_backed;
    }
   
    public Integer getCategory() {
		return category;
	}


	public void setCategory(Integer category) {
		this.category = category;
	}


	public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }
    public String getCategory_id() {
        return this.category_id;
    }
    
    public void setCategory_id(String category_id) {
        this.category_id = category_id;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    public String getProjects_backed() {
        return this.projects_backed;
    }
    
    public void setProjects_backed(String projects_backed) {
        this.projects_backed = projects_backed;
        try{
        	this.count = Integer.parseInt(projects_backed);
        }catch(Exception e)
        {
        	e.printStackTrace();
        }
    }
    

	public Integer getCount() {
		return count;
	}


	public void setCount(Integer count) {
		this.count = count;
	}


	@Override
	public String toString() {
		return "Breakup [id=" + id + ", profile=" + profile + ", categoryId="
				+ category_id + ", label=" + label + ", color=" + color
				+ ", path=" + path + ", projectsBacked=" + projects_backed + "]";
	}




}


