package db.dto;
// Generated Mar 4, 2013 12:27:59 AM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {



     private String url;
     private String name;
     private String joinedDate;
     private Integer art;
     private Integer comics;
     private Integer dance;
     private Integer design;
     private Integer fashion;
     private Integer filmandvideo;
     private Integer food;
     private Integer games;
     private Integer music;
     private Integer photography;
     private Integer publishing;
     private Integer technology;
     private Integer theator;
     private String location;
     private Integer totalProjects;
     private Integer created;
     private Set<Project> projects = new HashSet<Project>();
     private Integer ksId;
     
    public Integer getKsId() {
		return ksId;
	}

	public void setKsId(Integer ksId) {
		this.ksId = ksId;
	}

	public Set<Project> getProjects() {
		return projects;
	}

	public void setProjects(Set<Project> projectList) {
		this.projects = projectList;
	}

	public Integer getCreated() {
		return created;
	}

	public void setCreated(Integer created) {
		this.created = created;
	}

	public Profile() {
    }

    public Profile(String url, String name, String joinedDate) {
       this.url = url;
       this.name = name;
       this.joinedDate = joinedDate;
    }
   /*
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    } */
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getJoinedDate() {
        return this.joinedDate;
    }
    
    public void setJoinedDate(String joinedDate) {
        this.joinedDate = joinedDate;
    }

	public Integer getArt() {
		return art;
	}

	public void setArt(Integer art) {
		this.art = art;
	}

	public Integer getComics() {
		return comics;
	}

	public void setComics(Integer comics) {
		this.comics = comics;
	}

	public Integer getDance() {
		return dance;
	}

	public void setDance(Integer dance) {
		this.dance = dance;
	}

	public Integer getDesign() {
		return design;
	}

	public void setDesign(Integer design) {
		this.design = design;
	}

	public Integer getFashion() {
		return fashion;
	}

	public void setFashion(Integer fashion) {
		this.fashion = fashion;
	}

	public Integer getFilmandvideo() {
		return filmandvideo;
	}

	public void setFilmandvideo(Integer filmandvideo) {
		this.filmandvideo = filmandvideo;
	}

	public Integer getFood() {
		return food;
	}

	public void setFood(Integer food) {
		this.food = food;
	}

	public Integer getGames() {
		return games;
	}

	public void setGames(Integer games) {
		this.games = games;
	}

	public Integer getMusic() {
		return music;
	}

	public void setMusic(Integer music) {
		this.music = music;
	}

	public Integer getPhotography() {
		return photography;
	}

	public void setPhotography(Integer photography) {
		this.photography = photography;
	}

	public Integer getPublishing() {
		return publishing;
	}

	public void setPublishing(Integer publishing) {
		this.publishing = publishing;
	}

	public Integer getTechnology() {
		return technology;
	}

	public void setTechnology(Integer technology) {
		this.technology = technology;
	}

	public Integer getTheator() {
		return theator;
	}

	public void setTheator(Integer theator) {
		this.theator = theator;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public Integer getTotalProjects() {
		return totalProjects;
	}

	public void setTotalProjects(Integer totalProjects) {
		this.totalProjects = totalProjects;
	}

	@Override
	public String toString() {
		return "Profile [url=" + url + ", name=" + name
				+ ", joinedDate=" + joinedDate + ", art=" + art + ", comics="
				+ comics + ", dance=" + dance + ", design=" + design
				+ ", fashion=" + fashion + ", filmandvideo=" + filmandvideo
				+ ", food=" + food + ", games=" + games + ", music=" + music
				+ ", photography=" + photography + ", publishing=" + publishing
				+ ", technology=" + technology + ", theator=" + theator
				+ ", location=" + location + ", totalProjects=" + totalProjects
				+ "]";
	}
   
    
}


