package db.dto;
// Generated Mar 4, 2013 12:27:59 AM by Hibernate Tools 3.2.1.GA



/**
 * Reward generated by hbm2java
 */
public class Reward  implements java.io.Serializable {


     private Integer id;
     private Project project;
     private String amount;
     private String backers;

    public Reward() {
    }

	
    public Reward(Project project) {
        this.project = project;
    }
    public Reward(Project project, String amount, String backers) {
       this.project = project;
       this.amount = amount;
       this.backers = backers;
    }
    
    public Reward(String amount, String backers) {
       
        this.amount = amount;
        this.backers = backers;
     }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Project getProject() {
        return this.project;
    }
    
    public void setProject(Project project) {
        this.project = project;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }
    public String getBackers() {
        return this.backers;
    }
    
    public void setBackers(String backers) {
        this.backers = backers;
    }


	@Override
	public String toString() {
		return "Reward [id=" + id + ", amount=" + amount + ", backers="
				+ backers + "]";
	}




}


